version: '3'

tasks:
  default:
    cmds:
      - task: clean
      - task: sshql
      - task: postgres
      - task: mysql
      - task: test
      - task: nancy

  sshql:
    cmds:
      - go mod tidy -v -go=1.19
    sources:
      - ./go.work
      - ./go.mod
      - ./go.sum
      - '**/*.go'

  postgres:
    dir: pgdrv
    cmds:
      - go mod tidy -v -go=1.19
    sources:
      - ./go.work
      - ./go.mod
      - ./go.sum
      - '**/*.go'

  mysql:
    dir: mysqldrv
    cmds:
      - go mod tidy -v -go=1.19
    sources:
      - ./go.work
      - ./go.mod
      - ./go.sum
      - '**/*.go'

  clean:
    desc: Initialize module and build cache.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache

  test:
    desc: Test and lint.
    cmds:
      - go test -shuffle on ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.48.0 golangci-lint run --enable gosec --timeout 3m0s ./...
    sources:
      - ./go.work
      - '**/go.mod'
      - '**/go.sum'
      - '**/*.go'

  nancy:
    desc: Check vulnerability of external packages with Nancy.
    cmds:
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.work
      - '**/go.mod'
      - '**/go.sum'
      - '**/*.go'
