version: '3'

tasks:
  default:
    cmds:
      - task: clean
      - task: sshql
      - task: postgres
      - task: mysql

  sshql:
    cmds:
      - go mod tidy -v -go=1.19
      - go test -shuffle on ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.49.0 golangci-lint run --enable gosec --timeout 3m0s ./...
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  postgres:
    dir: pgdrv
    cmds:
      - go mod tidy -v -go=1.19
      - go test -shuffle on ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.49.0 golangci-lint run --enable gosec --timeout 3m0s ./...
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  mysql:
    dir: mysqldrv
    cmds:
      - go mod tidy -v -go=1.19
      - go test -shuffle on ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.49.0 golangci-lint run --enable gosec --timeout 3m0s ./...
      - depm list -j | nancy sleuth -n
    sources:
      - ./go.mod
      - '**/*.go'

  clean:
    desc: Initialize module and build cache.
    cmds:
      - rm -f ./go.sum
      - go clean -cache
      - go clean -modcache

  test:
    desc: Test and lint.
    cmds:
      - go test -shuffle on ./...
      - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.48.0 golangci-lint run --enable gosec --timeout 3m0s ./...

  nancy:
    desc: Check vulnerability of external packages with Nancy.
    cmds:
      - depm list -j | nancy sleuth -n

  tidy:
    desc: Remake go.sum file.
    cmds:
      - go mod tidy -v -go=1.19
